create database Hotel;
show databases;
use Hotel;
create table logi(username varchar(27), password varchar(27));
insert into logi value('admin', '123456');
select * from logi;
create table employee(name varchar(25), age varchar(25), gender varchar(10), job varchar(25), salary varchar(10), phone varchar(15), email varchar(40), aadhar varchar(15));
describe employee;
select * from employee;
create table addroom(room_no varchar(10), available varchar(20), cleaning_status varchar(20), price varchar(20), bed_type varchar(20));
describe addroom;
select * from addroom;
create table adddriver(name varchar(25),age varchar(25), gender varchar(25), Car_company varchar(25), Car_model varchar(25), available varchar(25), location varchar(25));
describe adddriver;
select gender, age, name  from adddriver;
select * from adddriver;
create table Customeradd(id varchar(25), number varchar(25), name varchar(25), gender varchar(25), country varchar(25), room_no varchar(25), time varchar(70), deposit varchar(25));
select * from Customeradd;
create table Department(department varchar(50), bugdet varchar(50));
insert into Department values ('Front Office', '50000');
insert into Department values ('House Keeping', '40000');
insert into Department values ('Food and Beverage', '23000' );
insert into Department values ('Kichen or Food production', '54000');
insert into Department values ('Security', '32000');
select * from Department;